language: rust
dist: trusty
sudo: false
group: beta

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - CARGO_FEATURES=python27-sys PYTHON_SYS_EXECUTABLE=python2
  - CARGO_FEATURES=python3-sys PYTHON_SYS_EXECUTABLE=python3
before_script:
  - 'export LD_LIBRARY_PATH="$($PYTHON_SYS_EXECUTABLE -c "import sysconfig; print(sysconfig.get_config_var(''LIBDIR''))"):$LD_LIBRARY_PATH"'
script:
  - cargo build --verbose --no-default-features --features $CARGO_FEATURES
  - cargo test --verbose --no-default-features --features $CARGO_FEATURES
